name: "Setup the node and R version"
description: "Prepare a CI environment for flowR"

inputs:
    node-version:
        description: "The node version to use"
        required: false
        default: "21.6.x"
    r-version:
        description: "The R version to use"
        required: false
        default: "4.3.2"


runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: Wandalen/wretry.action@master
      with:
        attempt_limit: 15
        attempt_delay: 10000
        action: actions/checkout@v4
        with: |
          submodules: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org/'

    - name: Setup R
      if: ${{ inputs.r-version != '' }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ inputs.r-version  }}

    - name: Install R packages
      if: ${{ inputs.r-version != '' }}
      shell: Rscript {0}
      run: install.packages("xmlparsedata", repos="https://cloud.r-project.org/")
